### ISSUE TITLE
Tweet text gets cut off if apostrophe present

### ISSUE THREAD

**Issue by devignerforhire** [wmdmark/jquery-proquo#2]
Hi Mark,

Great work on the plugin - it's exactly what I was after :)

One thing I noticed though, is that text with an apostraphe gets cut off 

Here is my sample quote block:

<blockquote class="tweetable-quote">
<p>When Seattleites say "Let's do something sometime" what they really mean is "Let's never do anything ever". <small>Liza May</small></p>
</blockquote>

Notice the Let's words. The text that would be added to the tweet is "Let".

Any ideas?

Thanks!
Chris

**Comment by j0narch3r** [comment]
I spent the last 30 minutes hacking at it to no avail. Same problem. (Tried grabbing `$(this).text()` in `getTweetText` and calling `.replace(/ ' /g, " \' " )` to escape the apostrophe. Couldn't get it to work though.

**Comment by wmdmark** [comment]
@j0narch3r @devignerforhire Just pushed a fix for this. Sorry for the delayed response @devignerforhire.

**Comment by j0narch3r** [comment]
That was so fast! Thanks a mil, @wmdmark. It's a really awesome plugin.
